version: '3.7'

services:
  api:
    build: .
    ports:
      - 80:8000
    links:
      - redis
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data: