[tool.poetry]
authors = ["Darkflame72 <31436575+Darkflame72@users.noreply.github.com>"]
description = ""
license = "AGPLv3"
name = "minecraft-api"
version = "1.0.0"

[tool.poetry.dependencies]
fastapi = "^0.61.1"
python = "^3.7"
uvicorn = "^0.12.2"
slowapi = "^0.1.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.790"
flake8 = "^3.8.4"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.2.0"]
