[tool.poetry]
authors = ["Darkflame72 <31436575+Darkflame72@users.noreply.github.com>"]
description = ""
license = "AGPLv3"
name = "minecraft-api"
version = "1.0.0"

[tool.poetry.dependencies]
fastapi = "^0.61.1"
python = "^3.7"
slowapi = "^0.1.2"
uvicorn = "^0.12.2"
celery = "^5.0.1"
pydantic = "^1.7.1"
gunicorn = "^20.0.4"
SQLAlchemy = "^1.3.20"
alembic = "^1.4.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
mypy = "^0.790"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
typeguard = "^2.10.0"
safety = "^1.9.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.2.0"]
