# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, account_mojang_com: str=None, api_mojang_com: str=None, authserver_mojang_com: str=None, textures_minecraft_net: str=None, minecraft_net: str=None, sessionserver_mojang_com: str=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param account_mojang_com: The account_mojang_com of this InlineResponse2002.  # noqa: E501
        :type account_mojang_com: str
        :param api_mojang_com: The api_mojang_com of this InlineResponse2002.  # noqa: E501
        :type api_mojang_com: str
        :param authserver_mojang_com: The authserver_mojang_com of this InlineResponse2002.  # noqa: E501
        :type authserver_mojang_com: str
        :param textures_minecraft_net: The textures_minecraft_net of this InlineResponse2002.  # noqa: E501
        :type textures_minecraft_net: str
        :param minecraft_net: The minecraft_net of this InlineResponse2002.  # noqa: E501
        :type minecraft_net: str
        :param sessionserver_mojang_com: The sessionserver_mojang_com of this InlineResponse2002.  # noqa: E501
        :type sessionserver_mojang_com: str
        """
        self.swagger_types = {
            'account_mojang_com': str,
            'api_mojang_com': str,
            'authserver_mojang_com': str,
            'textures_minecraft_net': str,
            'minecraft_net': str,
            'sessionserver_mojang_com': str
        }

        self.attribute_map = {
            'account_mojang_com': 'account.mojang.com',
            'api_mojang_com': 'api.mojang.com',
            'authserver_mojang_com': 'authserver.mojang.com',
            'textures_minecraft_net': 'textures.minecraft.net',
            'minecraft_net': 'minecraft.net',
            'sessionserver_mojang_com': 'sessionserver.mojang.com'
        }
        self._account_mojang_com = account_mojang_com
        self._api_mojang_com = api_mojang_com
        self._authserver_mojang_com = authserver_mojang_com
        self._textures_minecraft_net = textures_minecraft_net
        self._minecraft_net = minecraft_net
        self._sessionserver_mojang_com = sessionserver_mojang_com

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_mojang_com(self) -> str:
        """Gets the account_mojang_com of this InlineResponse2002.


        :return: The account_mojang_com of this InlineResponse2002.
        :rtype: str
        """
        return self._account_mojang_com

    @account_mojang_com.setter
    def account_mojang_com(self, account_mojang_com: str):
        """Sets the account_mojang_com of this InlineResponse2002.


        :param account_mojang_com: The account_mojang_com of this InlineResponse2002.
        :type account_mojang_com: str
        """

        self._account_mojang_com = account_mojang_com

    @property
    def api_mojang_com(self) -> str:
        """Gets the api_mojang_com of this InlineResponse2002.


        :return: The api_mojang_com of this InlineResponse2002.
        :rtype: str
        """
        return self._api_mojang_com

    @api_mojang_com.setter
    def api_mojang_com(self, api_mojang_com: str):
        """Sets the api_mojang_com of this InlineResponse2002.


        :param api_mojang_com: The api_mojang_com of this InlineResponse2002.
        :type api_mojang_com: str
        """

        self._api_mojang_com = api_mojang_com

    @property
    def authserver_mojang_com(self) -> str:
        """Gets the authserver_mojang_com of this InlineResponse2002.


        :return: The authserver_mojang_com of this InlineResponse2002.
        :rtype: str
        """
        return self._authserver_mojang_com

    @authserver_mojang_com.setter
    def authserver_mojang_com(self, authserver_mojang_com: str):
        """Sets the authserver_mojang_com of this InlineResponse2002.


        :param authserver_mojang_com: The authserver_mojang_com of this InlineResponse2002.
        :type authserver_mojang_com: str
        """

        self._authserver_mojang_com = authserver_mojang_com

    @property
    def textures_minecraft_net(self) -> str:
        """Gets the textures_minecraft_net of this InlineResponse2002.


        :return: The textures_minecraft_net of this InlineResponse2002.
        :rtype: str
        """
        return self._textures_minecraft_net

    @textures_minecraft_net.setter
    def textures_minecraft_net(self, textures_minecraft_net: str):
        """Sets the textures_minecraft_net of this InlineResponse2002.


        :param textures_minecraft_net: The textures_minecraft_net of this InlineResponse2002.
        :type textures_minecraft_net: str
        """

        self._textures_minecraft_net = textures_minecraft_net

    @property
    def minecraft_net(self) -> str:
        """Gets the minecraft_net of this InlineResponse2002.


        :return: The minecraft_net of this InlineResponse2002.
        :rtype: str
        """
        return self._minecraft_net

    @minecraft_net.setter
    def minecraft_net(self, minecraft_net: str):
        """Sets the minecraft_net of this InlineResponse2002.


        :param minecraft_net: The minecraft_net of this InlineResponse2002.
        :type minecraft_net: str
        """

        self._minecraft_net = minecraft_net

    @property
    def sessionserver_mojang_com(self) -> str:
        """Gets the sessionserver_mojang_com of this InlineResponse2002.


        :return: The sessionserver_mojang_com of this InlineResponse2002.
        :rtype: str
        """
        return self._sessionserver_mojang_com

    @sessionserver_mojang_com.setter
    def sessionserver_mojang_com(self, sessionserver_mojang_com: str):
        """Sets the sessionserver_mojang_com of this InlineResponse2002.


        :param sessionserver_mojang_com: The sessionserver_mojang_com of this InlineResponse2002.
        :type sessionserver_mojang_com: str
        """

        self._sessionserver_mojang_com = sessionserver_mojang_com
