# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, trivia: List[str]=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param trivia: The trivia of this InlineResponse2003.  # noqa: E501
        :type trivia: List[str]
        """
        self.swagger_types = {
            'trivia': List[str]
        }

        self.attribute_map = {
            'trivia': 'trivia'
        }
        self._trivia = trivia

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def trivia(self) -> List[str]:
        """Gets the trivia of this InlineResponse2003.


        :return: The trivia of this InlineResponse2003.
        :rtype: List[str]
        """
        return self._trivia

    @trivia.setter
    def trivia(self, trivia: List[str]):
        """Sets the trivia of this InlineResponse2003.


        :param trivia: The trivia of this InlineResponse2003.
        :type trivia: List[str]
        """

        self._trivia = trivia
